version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errorlint
    - govet
    - ineffassign
    - nilerr
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
