package runtime

import (
	"bytes"
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/fibegg/fibe-distilled/internal/domain"
)

// LocalExecutor runs runtime shell commands on the same host as fibe-distilled.
type LocalExecutor struct{}

// Run executes one local shell command and keeps stdout/stderr separated.
func (e LocalExecutor) Run(ctx context.Context, _ domain.Marquee, command string) (CommandResult, error) {
	// #nosec G204 -- runtime commands are generated by fibe-distilled's local Docker/Compose boundary and validated before construction.
	cmd := exec.CommandContext(ctx, "sh", "-lc", command)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	result := CommandResult{
		Stdout: stdout.String(),
		Stderr: stderr.String(),
	}
	if err != nil {
		if exitErr, ok := errors.AsType[*exec.ExitError](err); ok {
			result.ExitCode = exitErr.ExitCode()
		} else {
			result.ExitCode = 1
		}
	}
	return result, err
}

// WriteFile writes content to one local runtime path.
func (e LocalExecutor) WriteFile(ctx context.Context, _ domain.Marquee, remotePath string, content string) (CommandResult, error) {
	if err := ctx.Err(); err != nil {
		return CommandResult{Stderr: err.Error(), ExitCode: 1}, err
	}
	if err := os.MkdirAll(filepath.Dir(remotePath), 0o700); err != nil {
		return CommandResult{Stderr: err.Error(), ExitCode: 1}, err
	}
	if err := os.WriteFile(remotePath, []byte(content), 0o600); err != nil {
		return CommandResult{Stderr: err.Error(), ExitCode: 1}, err
	}
	return CommandResult{}, nil
}
